export enum AuthError {

    UNAUTHORIZED_GOOGLE_TOKEN="UNAUTHORIZED_GOOGLE_TOKEN",
    UNAUTHORIZED_ACCESS_TOKEN="UNAUTHORIZED_ACCESS_TOKEN",
    EXPIRED_ACCESS_TOKEN="EXPIRED_ACCESS_TOKEN",

    UNAUTHORIZED_REFRESH_TOKEN="UNAUTHORIZED_REFRESH_TOKEN",
    EXPIRED_REFRESH_TOKEN="EXPIRED_REFRESH_TOKEN",
}